### ISSUE TITLE
Incorrect username or password! Please try again.

### ISSUE THREAD

**Issue by ithabetz** [theraw/xtreamui-on-docker#1]
After start container via docker-compose get wrong password message
after some investigation, I found that MySQL services stop and failed to start.

**Comment by theraw** [comment]
yes for some reason sometimes services fail to start so this will require for you to manually start mysql 

if container goes totally offline open `docker-compose.yml` and replace 
```command: ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]```
with
```command: ["/usr/sbin/sshd", "-D"]```
then re'create your container,

this will keep container online even if services fail to start, you can then `docker exec -it xui bash` and start services
