### ISSUE TITLE
404 on Playlist Request

### ISSUE THREAD

**Issue by 0x41mmarVM** [theraw/xtreamui-on-docker#12]
Hi, thank you for the amazing work.

I'm facing a bizarre problem. I basically start the container, all works, nothing interesting. I try to download the playlist of the included user and it works, but once I change the password, or create a new user, all I get is 404.

The URL I'm trying to access is 

http://[IP]:25461/get.php?username=test2&password=[correctPassword]&type=simple&output=hls

**Comment by theraw** [comment]
this project is to setup xtream ui on a container, fixing such problems u should ask somewhere else i'm not the one to help you with this. i'm not xtreamui support!

**Comment by 0x41mmarVM** [comment]
Hmm.. I assumed since this was such a minimal test (start up, change password, error) that the issue must be with the container or its running. Confirmation that this is not the case is helpful information in and of itself, since I can keep trying within the control panel. Thank you for your help.

**Comment by theraw** [comment]
my point was to install xtream-ui into a docker container so i did, how it works its not my problem but xtreamui developers problem.

Their code is encoded and really badly developed even when they decide to stop supporting this project they didn't giveaway their source code so someone else could take it and keep developing.
They shared a bad code, and when ppl start to complain they will ask you to pay them for everything they fix (fixing their mistakes). so i didn't bother with that. and i suggest if you have no idea what you're doing or any idea about linux/php/coding/nginx find some easier panel to use or you'll need bunch of money to make this crap work
