### ISSUE TITLE
"./xui.yml" is unsupported

### ISSUE THREAD

**Issue by mickflix** [theraw/xtreamui-on-docker#7]
I get This error when running docker-compose

 Version in "./xui.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by theraw** [comment]
you need docker compose v3+
https://docs.docker.com/compose/install/

**Comment by theraw** [comment]
for now you can also use https://github.com/theraw/xtreamui-on-docker/blob/master/portainer-composerV2.yml 

But in next releases docker-compose v2 will not be supported by me since the way how it assigns static private ip is different from v3.

**Comment by mickflix** [comment]
Cheers for the speedy reply, managed to install :) is it just the front end panel - options for adding vod mag devices etc are not available

**Comment by theraw** [comment]
It's a old version, you should update, the current version on docker container wasn't meant for production only development to test if services start

**Comment by theraw** [comment]
You should be careful even his own creator GTA doesn't know what's doing many ppl are getting hacked that's the main reason i paused my work with this project.
